# Generated by Django 6.0.2 on 2026-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityprofile',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='accessibilityprofile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessibilityprofile',
            name='subtitles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('VISUAL', 'Discapacidad visual'), ('AUDITIVA', 'Discapacidad auditiva')], max_length=20, null=True),
        ),
    ]
