# Generated by Django 6.0.2 on 2026-02-10 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_accessibilityprofile_font_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityprofile',
            options={'verbose_name': 'Perfil de Accesibilidad', 'verbose_name_plural': 'Perfiles de Accesibilidad'},
        ),
        migrations.AddField(
            model_name='accessibilityprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('VISUAL', 'Discapacidad visual'), ('AUDITIVA', 'Discapacidad auditiva'), ('NINGUNA', 'Ninguna')], max_length=20, null=True, verbose_name='Tipo de Discapacidad'),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=3, help_text='De 1 (muy pequeño) a 5 (muy grande)', verbose_name='Tamaño de Fuente'),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='high_contrast',
            field=models.BooleanField(default=False, verbose_name='Alto Contraste'),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='subtitles',
            field=models.BooleanField(default=True, verbose_name='Subtítulos Automáticos'),
        ),
        migrations.AlterField(
            model_name='accessibilityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
