# Generated by Django 6.0.2 on 2026-02-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Texto'), ('video', 'Video (URL/ID)'), ('image', 'Imagen'), ('file', 'Archivo PDF/Documento'), ('assessment', 'Evaluación/Lección')], default='text', max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module')),
            ],
            options={
                'verbose_name': 'Contenido de Módulo',
                'verbose_name_plural': 'Contenidos de Módulos',
                'ordering': ['order'],
            },
        ),
    ]
