# Generated by Django 6.0.2 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ai_accessibility_text',
            field=models.TextField(blank=True, help_text='Aquí se guardará el OCR del PDF o la descripción de la imagen generada por IA.', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_processed_by_ia',
            field=models.BooleanField(default=False, help_text='Indica si la IA ya analizó este contenido.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texto'), ('video', 'Video (YouTube/URL)'), ('image', 'Imagen'), ('file', 'Archivo PDF/Documento'), ('assessment', 'Evaluación/Lección')], default='text', max_length=20),
        ),
    ]
